import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto, Outfit } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'

// If loading a variable font, you don't need to specify the font weight
const outfit = Outfit({ subsets: ['latin'] })
const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Taxi Booking',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={roboto.className}>
					<Navbar />
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
